# Numpy

In [3]:
import numpy as np
# initializing an array

a = np.array([1, 2, 3, 4, 5, 6]) # using a list
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) # using nested sequences
c = np.array([[[0, 1, 2, 3], # array of shape (3,2,4), ndim = 3
                [4, 5, 6, 7]],
              [[0, 1, 2, 3],
               [4, 5, 6, 7]],
              [[0 ,1 ,2, 3],
               [4, 5, 6, 7]]])

# accessing elements

a[0] # 0-indexed
a[:3] 
b[1, 3]

# setting values
a[0] = 10

# array attributes

a.ndim
a.shape  # output: tuple of non-neg integers (num rows, num cols)
len(a.shape) == a.ndim # true
a.size # total number of elements in the array
a.dtype # "int" for integer, "64" for 64-bit

dtype('int64')

In [4]:
# creating arrays

np.zeros(4)
np.ones(4)
np.empty(4) # random numbers 
x = np.ones(2, dtype=np.int64) # can specify dtype, default is np.float64
np.arange(2, 9, 2) # evenly spaced intervals (first number, last number, step size) output: 
np.linspace(0,10, num=5) # spaced linearly in specified interval (including endpoints)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
# Sorting, adding, removing elements

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr) # in ascending order

# merging

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

# reshaping

a = np.arange(6)
print(f"a: \n{a}")
b = a.reshape(3, 2)
print(f"b: \n{b}")

a: 
[0 1 2 3 4 5]
b: 
[[0 1]
 [2 3]
 [4 5]]
